#!/usr/bin/python
# -*- coding: utf8 -*-

#
# Authors:	Xinwei Hu <xwhu@suse.de>
#		Lukas Ocilka <locilka@suse.cz>
#
# File:		ag_multipath
#
# License:
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#   See the GNU General Public License for more details.
#   
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version
#   2 of the License, or (at your option) any later version.
#   
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
#   02111-1307 USA
#

import gettext, os, re
from gettext import textdomain
textdomain("openais")

# python bindings will be droped
# delete all python bindings

#from ycp import *
import copy
import sys


#the option table is used to parse and write suggested_value if no options are read

#default_value is used in file_parser, if input has the option, but failed to parse,
#use the default_value.

#suggested_value is used in file printing, if we do not parse any from input, but The
#option has suggested_value, print it.

totem_option_table = {
	"version":{"doc":"The only valid version is 2",
		   "type":"int",
		   "default_value":2,
		   "suggested_value":2},
	"crypto_cipher":{"doc":"Used for mutual node authentication",
		"type":"select[aes256, aes192, aes128 and 3des,none]","default_value":"none",
		},
	"crypto_hash":{"doc":"Used for mutual node authentication",
		"type":"select[none,md5,sha1,sha256,sha384,sha512]","default_value":"none",
		},
	"clear_node_high_bit":{"doc":"To make sure the auto-generated nodeid is positive",
			       "default_value":"yes"},
	"cluster_name":{"doc":"This specifies the name of cluster","type":"string","default_value":"cluster"},
	"secauth":{"doc":"HMAC/SHA1 should be used to authenticate all message",
		   "default_value":"off"},
	"rrp_mode":{"doc":"The mode for redundant ring. None is used when only 1 interface specified, otherwise, only active or passive may be choosen",
		    "type":"select[none,active,passive]", "default_value":"none"},
	"netmtu":{"doc":"Size of MTU", "type":"int", "default_value":1500},
	"threads":{"doc":"How many threads should be used to encypt and sending message. Only have meanings when secauth is turned on",
		   "type":"int", "default_value":0},
	"vsftype":{"doc":"The virtual synchrony filter type used to indentify a primary component. Change with care.",
		   "default_value":"ykd",
		   "suggested_value":"none"},
	"token":{"doc":"Timeout for a token lost. in ms",
		 "type":"int", "default_value":1000,
		 "suggested_value":5000},
	"token_retransmit":{"doc":"How long before receving a token then token is retransmitted. Don't change this value.",
			    "type":"int", "default_value":238},
	"hold":{"doc":"How long the token should be held by representative when protocol is under low utilization. Don't change this value.",
		"type":"int", "default_value":180},
	"token_retransmits_before_loss_const":{"doc":"How many token retransmits should be attempted before forming a new configuration.",
					       "type":"int", "default_value":4,
					       "suggested_value":10},
	"join":{"doc":"How long to wait for join messages in membership protocol. in ms",
		"type":"int", "default_value":50,
		"suggested_value":60},
	"send_join":{"doc":"This timeout specifies in milliseconds an upper range between 0 and send_join to wait before sending a join message.",
		     "type":"int", "default_value":0},
	"consensus":{"doc":"How long to wait for consensus to be achieved before starting a new round of membership configuration.",
		     "type":"int", "default_value":3600,
		     "suggested_value":6000},
	"merge":{"doc":"How long to wait before checking for a partition when no multicast traffic is being sent.",
		 "type":"int", "default_value":200},
	"downcheck":{"doc":"How long to wait before checking that a network interface is back up after it has been downed.",
		     "type":"int", "default_value":1000},
	"fail_to_recv_const":{"doc":"How many rotations of the token without receiving any of the messages when messages should be received may occur before a new configuration is formed",
			      "type":"int", "default_value":50},
	"seqno_unchanged_const":{"doc":"How many rotations of the token without any multicast traffic should occur before the merge detection timeout is started.",
				 "type":"int", "default_value":30},
	"heartbeat_failure_allowed":{"doc":"Configures the optional HeartBeating mechanism for faster failure detection. 0 for disable.", "type":"int", "default_value":0},
	"max_network_delay":{"doc":"The approximate delay that your network takes to transport one packet from one machine to another.",
			     "type":"int", "default_value":50},
	"window_size":{"doc":"The maximum number of messages that may be sent on one token rotation.",
		       "type":"int", "default_value":50},
	"max_messages":{"doc":"The maximum number of messages that may be sent by one processor on receipt of the token.",
			"type":"int", "default_value":17,
			"suggested_value":20},
	"rrp_problem_count_timeout":{"doc":"The time in milliseconds to wait before decrementing the problem count by 1 for a particular ring to ensure a link is not marked faulty for transient network failures.",
				     "type":"int", "default_value":2000},
	"rrp_problem_count_threshhold":{"doc":"The number of times a problem is detected with a link before setting the link faulty.",
					"type":"int", "default_value":10},
	"rrp_token_expired_timeout":{"doc":"This specifies the time in milliseconds to increment the problem counter for the redundant ring protocol after not having received a token from all rings for a particular processor.", "type":"int", "default_value":47},
	"transport":{"doc":"", "type":"select[udp,udpu]","default_value":"udp"},
}




interface_option_table = {
	"ringnumber":{"doc":"The ringnumber assigned to this interface setting", "default_value":0, "type":"int"},
	"bindnetaddr":{"doc":"Network Address to be bind for this interface setting", "default_value":0},
	"mcastaddr":{"doc":"The multicast address to be used", "default_value":0},
	"mcastport":{"doc":"The multicast port to be used", "default_value":0, "type":"int"},
	"ttl":{"doc":"Time-to-live for cluster communication packets", "type":"int", "default_value":1}
	}


#only has two rings at most
node_option_table = {
		"ring0_addr":{"doc":"ring0 address", "type":"string", "default_value":"0"},
		"ring1_addr":{"doc":"ring1 address","type":"string", "default_value":"0"},
		"nodeid":{"doc":"required in ipv6, optional in ipv4","type":"string"},
}

logging_option_table = {
	"debug":{"doc":"Whether or not turning on the debug information in the log", "default_value":"off",
		 "suggested_value":"off"},
	"fileline":{"doc":"Logging file line in the source code as well", "default_value":"off",
		    "suggested_value":"off"},
	"to_syslog":{"doc":"Log to syslog", "default_value":"yes",
		     "suggested_value":"yes"},
	"to_stderr":{"doc":"Log to the standard error output", "default_value":"no", "suggested_value":"no"},
	"to_logfile":{"doc":"Log to a specified file", "default_value":"no", "suggested_value":"no"},
	"logfile":{"doc":"Log to be saved in this specified file", "default_value":"/tmp/saved_pacemaker_log"},
	"syslog_facility":{"doc":"Facility in syslog", "default_value":"daemon", "suggested_value":"daemon"},
	"timestamp":{"doc":"Log timestamp as well", "default_value":"off", "suggested_value":"off"},
}

logger_subsys_option_table = {
	"subsys":{"doc":"This specifies the subsystem identity (name) for which logging is specified", "default_value":"QUORUM"},
	"debug":{"doc":"Enable debug for this logger.", "default_value":"on"},
	}


quorum_option_table = {
		"provider":{"doc":"Enable and configure quorum subsystem","type":"string", "default_value":"corosync_votequorum","suggested_value":"corosync_votequorum"},
		"expected_votes":{"doc":"votequorum requires an expected_votes value to function","default_value":""},
		"two_node":{"doc":"Enables two node cluster operations"},
		"wait_for_all":{"doc":"Enables Wait For All (WFA) feature", "type":"int", "default_value":0},
		"last_man_standing":{"doc":"Enables Last Man Standing (LMS) feature (default: 0)", "type":"int","default_value":0},
		"last_man_standing_window":{"type":"int","default_value":10000},
		"auto_tie_breaker":{"doc":"Enables Auto Tie Breaker (ATB) feature", "type":"int", "default_value":0},
		"allow_downscale":{"doc":"Enables allow downscale (AD) feature","type":"int", "default_value":0},
		}

qb_option_table = { "ipc_type":{"doc":"This specifies type of IPC to use",
		    "type":"string", "default_value":"native"}
		  }

totem_options = {"interface":[]}
logging_options = {"logger_subsys":[]}
quorum_options={}
nodelist_options={"node":[]}
qb_options={}

def strip_comments_and_pending_space(line):
	return line.split('#')[0].rstrip().lstrip()

def get_next_line(ff):
	l = ff.next()
	return strip_comments_and_pending_space(l)


def fulfill_default_logging_options ():
	for opt in logging_option_table.keys():
		if opt == "logger": continue
		sv = logging_option_table[opt].get("suggested_value", None)
		v = logging_options.get(opt, None)
		if v == None and sv != None:
			logging_options[opt] = sv

def fulfill_suggested_totem_options():
	totem_options["version"] = 2
	for opt in totem_option_table.keys():
		if opt == "interface": continue
		sv = totem_option_table[opt].get("suggested_value", None)
		v = totem_options.get(opt, None)
		if v == None and sv != None:
			totem_options[opt] = sv
			
def fulfill_suggested_quorum_options():
	# must has provider
	for opt in ['provider']:
		sv = quorum_option_table[opt].get("suggested_value", None)
		v = quorum_options.get(opt, None)
		if v == None and sv != None:
			quorum_options[opt] = sv

def print_quorum_options(f):
	f.write("quorum {\n");
	for key in quorum_options.keys():
		if quorum_options[key] == "":
			continue
		else:
			f.write("\t#%s\n\n" % (quorum_option_table[key]["doc"]))
			f.write("\t%s:\t%s\n\n" % (key, quorum_options[key]))
	f.write("}\n")

def print_qb_options(f):
	if(len(qb_options) == 0):
		return
	f.write("qb {\n");
	for key in qb_options.keys():
		f.write("\t#%s\n\n" % (qb_option_table[key]["doc"]))
		f.write("\t%s:\t%s\n\n" % (key, qb_options[key]))
	f.write("}\n")

def print_nodelist_options(f):
	nodelist = nodelist_options["node"]
	if len(nodelist) ==  0:
		return
	f.write("nodelist {\n");
	for node in nodelist:
		f.write("\tnode {\n")
		for key in node.keys():
			f.write("\t#%s\n" % (node_option_table[key]["doc"]))
			f.write("\t%s:\t%s\n\n" % (key, node[key]))
		f.write("\t}\n")
	f.write("}\n")

			
def print_logging_options(f):
	f.write("logging {\n")
	for key in logging_options.keys():
		if key == "logger_subsys":
			for log in logging_options["logger_subsys"]:
				f.write("\tlogger_subsys {\n")
				for l in log.keys():
					f.write("\t\t#%s\n\n" % (logger_subsys_option_table[l]["doc"]))
					f.write("\t\t%s:\t%s\n\n" % (l, log[l]))
				f.write("\t}\n")
			continue
		f.write("\t#%s\n\n" % (logging_option_table[key]["doc"]))
		f.write("\t%s:\t%s\n\n" % (key, logging_options[key]))
	f.write("}\n")

def print_totem_options(f):

	f.write("totem {\n")
	transport_protocol = totem_options.get("transport", "udp")
	for key in totem_options.keys():
		if key == "interface":
			for inf in totem_options["interface"]:
				f.write("\tinterface {\n")
				for k in inf.keys():
					if inf[k] == "":
						continue;
					else:
						f.write("\t\t#%s\n\n" % (interface_option_table[k]["doc"]))
						f.write("\t\t%s:\t%s\n\n" % (k, inf[k]))
				f.write("\t}\n")
			continue
		if totem_options[key] == "":
			continue
		f.write("\t#%s\n\n" % (totem_option_table[key]["doc"]))
		f.write("\t%s:\t%s\n\n" % (key, totem_options[key]))
	# We print out all possible configurations as well
	# dont for now. looking for better solution
	"""
	for opt in totem_option_table.keys():
		v = totem_options.get(opt, None)
		if v == None:
			f.write("\t#%s\n\n" % (totem_option_table[opt]["doc"]))
			f.write("\t#%s:\t%s\n\n" % (opt, totem_option_table[opt]["default_value"]))
	"""
	f.write("}\n")

def file_parser(file):
	global totem_options
	global logging_options
	global nodelist_options
	global qb_options
	global quorum_options
	
	for l in file:
		i = strip_comments_and_pending_space(l)
		if i == "":
			continue

		if i[-1] == "{":
			i = i[:-1].rsplit()[0]
			if i == "totem":
				totem_options = opt_parser(file, totem_option_table)
			elif i == "logging":
				logging_options = opt_parser(file, logging_option_table)
			elif i == "nodelist":
				nodelist_options = opt_parser(file, {})
			elif i == "quorum":
				quorum_options = opt_parser(file, quorum_option_table)
			elif i == "qb":
				qb_options = opt_parser(file, qb_option_table)
			else:
				pass
	
def opt_parser(file, options):
	result = {}
	i = ""
	while (i == ""):
		i = get_next_line(file)

	while (i[-1] != "}"):
		if (i[-1] == "{"):
			if i.lstrip().split(" ")[0] == "interface":
				infs = result.get("interface", [])
				infs.append(opt_parser(file, interface_option_table))
				result["interface"] = infs
			elif i.lstrip().split(" ")[0] == "logger_subsys":
				logs = result.get("logger_subsys", [])
				logs.append(opt_parser(file, logger_subsys_option_table))
				result["logger_subsys"] = logs
			elif i.lstrip().split(" ")[0] == "node":
				members = result.get("node", [])
				members.append(opt_parser(file, node_option_table))
				result["node"] = members
			else:
				#y2warning("Unknown sub-directive %s found. Ignore it" % (i.lstrip().split(" ")[0]))
				while (i[-1] != "}"):
					i = get_next_line(file)
				
			i = get_next_line(file)
			while ( i == ""):
				i = get_next_line(file)
			continue
		
		opt = i.split(":")
		try:
			doc = options[opt[0].strip()]["doc"]
		except KeyError:
			#y2warning("Unknown options %s"%opt[0].strip())
			pass
		else:
			if options[opt[0].strip()].get("type", "string") == "int":
				try:
					result[opt[0].strip()] = int(opt[1].strip())
				except ValueError:
					#y2warning("Invalid option %s found, default to %s" % (opt[0].strip(), options[opt[0].strip()]["default_value"]))
					result[opt[0].strip()] = options[opt[0].strip()]["default_value"]
			else:
				result[opt[0].strip()] = opt[1].strip()
		i = ""
		while (i == ""):
			i = get_next_line(file)

	return result.copy()

def validate_conf():
	if totem_options.get("version", 0) != 2:
		return 1, "Version has to be set to 2"
	inf1 = get_interface(0)
	inf2 = get_interface(1)
	if inf1 == None and inf2 != None:
		return 1, "Ringnumber 1 is specified while ringnumber 0 is not"
	if len(totem_options.get("interface", [])) == 0:
		return 1, "No interface specified"
	if len(totem_options.get("interface", []))>2:
		return 1, "More then 2 interfaces specified"
	for inf in totem_options["interface"]:
		if inf.get("mcastaddr", "") == "":
			return 1, "No multicast address specified"
		if inf.get("mcastport", 0) == 0:
			return 1, "No multicast port specified"
		if inf.get("ringnumber", -1) != 0 and inf.get("ringnumber", -1) != 1:
			return 1, "Ring Number must be 0 or 1, but got %d" %(inf.get("ringnumber", -1))
		try:
			inf.get("mcastaddr", "").index(':')
			if totem_options.get("nodeid", 0) == 0:
				return 1, "Node ID must be specified for IPv6"
		except ValueError:
			pass
	return 0, "OK"

def get_interface(i):
	for inf in totem_options.get("interface", []):
		if inf["ringnumber"] == i:
			return inf
	else:
		return None

def generateMemberString(ringnum):
	member_str = ""

	ring_address = "ring%d_addr" % ringnum
	#filter all nodes in a same ring
	for item in  nodelist_options.get("node"):
		if item.has_key(ring_address):
			address = item.get(ring_address, None)
			nodeid = item.get("nodeid", None)
			member_str += address
			if nodeid:
				member_str = member_str + ":" + nodeid
			member_str = member_str + " "
	return '"%s"' % member_str.strip()

def del_interface(k):
	for i in range(len(totem_options["interface"])):
		if totem_options["interface"][i]["ringnumber"] == k:
			del totem_options["interface"][i]
			break
		
def load_ais_conf(filename):
	try:
		f = open(filename, "r")
		file_parser(f)
		f.close()
	except:
		try:
			os.rename(filename, "/etc/corosync/corosync.conf.corrupted");
		except:
			pass
		try:
			f = open(filename+".example", "r")
			file_parser(f)
			f.close()
			return
		except:
			pass


class OpenAISConf_Parser:
	def __init__(self):
		load_ais_conf("/etc/corosync/corosync.conf")
    
	def doList(self, path):
		#remove the leading dot
		path_arr = path
	
		if path_arr[0] == '':
			return '["quorum", "totem", "nodelist"]'
		elif path_arr[0] == 'totem':
			if len(path_arr) == 1:
				return '["crypto_cipher","crypto_hash","secauth", "autoid", "threads", "rrpmode", "transport", "interface", "cluster_name"]'
			else:
				if path_arr[1] == 'interface':
					if len(path_arr) == 2:
						r = '[ '
						if get_interface(0) != None:
							r = r + '"interface0"'
							if get_interface(1) != None:
								r = r +  ', "interface1"'
						r = r + ']'
						return r
					else:
						if len(path_arr) == 3:
							if path_arr[2] == "interface0" and get_interface(0) != None:
								return '["bindnetaddr", "mcastaddr", "mcastport","ttl"]'
							elif path_arr[2] == "interface1" and get_interface(1) != None:
								return ' ["bindnetaddr", "mcastaddr", "mcastport", "ttl"]'
							else:
								return '[]'
						else:
							return '[]'
				else:
					return '[]'
		else:
			return 'nil\n'
	
	def doRead(self, path):
		if path[0] == "":
			return "nil\n"
		elif path[0] == "quorum" and len(path) >= 2:
			if path[1] == "expected_votes":
				return '"%s"' % quorum_options.get("expected_votes", "nil")
			else:
				return "nil"
		elif path[0] == "totem":
			if len(path) == 1:
				return "nil"
			elif len(path) == 2:
				if path[1] == "secauth":
					return '"%s"' % totem_options.get("secauth", "")
				elif path[1] == "autoid":
					#FIXME, check nodelist has nodeid
					for i in nodelist_options.get('node'):
						if i.has_key('nodeid'):
							return '"no"'
					return '"%s"' % totem_options.get("clear_node_high_bit", "yes")
				elif path[1] == "threads":
					return '"%d"' % totem_options.get("threads", 0)
				elif path[1] == "rrpmode":
					return '"%s"' % totem_options.get("rrp_mode", "none")
				elif path[1] == "transport":
					return '"%s"' % totem_options.get("transport", "udp")
				elif path[1] == "cluster_name":
					return '"%s"' % totem_options.get("cluster_name", "cluster")
				else:
					return "nil"
			elif len(path) == 4:
				if path[1] == "interface":
					if path[2] == "interface0":
						i = get_interface(0)
						if i == None:
							return "nil"
						else:
							if path[3] == "bindnetaddr":
								return '"%s"' % i.get("bindnetaddr", "")
							elif path[3] == "mcastaddr":
								return '"%s"' % i.get("mcastaddr", "")
							elif path[3] == "mcastport":
								return '"%d"' % i.get("mcastport", 5405)
							if path[3] == "ttl":
								return '"%d"' % i.get("ttl", 1)
							elif path[3] == "member":
								return generateMemberString(0)
							else:
								return "nil"
					elif path[2] == "interface1":
						i = get_interface(1)
						if i == None:
							return "nil"
						else:
							if path[3] == "bindnetaddr":
								return '"%s"' % i.get("bindnetaddr", "")
							elif path[3] == "mcastaddr":
								return '"%s"' % i.get("mcastaddr", "")
							elif path[3] == "mcastport":
								return '"%d"' % i.get("mcastport", 5405)
							elif path[3] == "member":
								return generateMemberString(1)
							else:
								return "nil"
					else:
						return "nil"
				else:
					return "nil"
			else:
				return "nil"
		else:
			return "nil"


	def saveFile(self):

		fulfill_default_logging_options()
		fulfill_suggested_totem_options()
		fulfill_suggested_quorum_options()

		f = open("/etc/corosync/corosync.conf.YaST2", "w")
		print_totem_options(f)
		print_nodelist_options(f)
		print_logging_options(f)
		print_quorum_options(f)
		print_qb_options(f)
		f.close()

		try:
			os.rename("/etc/corosync/corosync.conf", "/etc/corosync/corosync.conf.YasT2.bak")
		except OSError:
			pass
		try:
			os.rename("/etc/corosync/corosync.conf.YaST2", "/etc/corosync/corosync.conf")
		except OSError:
			pass
		pass

	def doWrite(self, path, args):
		if path[0] == "":
			self.saveFile()
		elif path[0] == "quorum":
			if path[1] == "expected_votes":
				quorum_options["expected_votes"] = args
				return "true"
		elif path[0] == "totem":
			if len(path) == 2:
				if path[1] == "autoid":
					totem_options["clear_node_high_bit"] = args
					return "true"
				elif path[1] == "secauth":
					totem_options["secauth"] = args
					return "true"
				elif path[1] == "threads":
					if args == "":
						if totem_options.get("threads", None) != None:
							del totem_options["threads"]
						return "true"
					try:
						totem_options["threads"] = int(args)
						return "true"
					except ValueError:
						return "false"
				elif path[1] == "rrpmode":
					totem_options["rrp_mode"] = args
					return "true"
				elif path[1] == "transport":
					totem_options["transport"] = args
					return "true"
				elif path[1] == "cluster_name":
					totem_options["cluster_name"] = args
					return "true"
				else:
					return "false"
			elif len(path) == 3:
				if path[1] == "interface":
					if args == "":
						if path[2] == "interface0":
							#y2debug("deleting interface 0")
							del_interface(0)
							return "true"
						elif path[2] == "interface1":
							#y2debug("deleting interface 1")
							del_interface(1)
							return "true"
						else:
							return "false"
					else:
						return "false"
				else:
					return "false"
			elif len(path) == 4:
				ring_num = 0
				if path[1] == "interface":
					i = None
					if path[2] == "interface0":
						i = get_interface(0)
						ring_num = 0
						if i == None:
							totem_options["interface"].append({"ringnumber":0})
							i = get_interface(0)
					elif path[2] == "interface1":
						ring_num = 1
						i = get_interface(1)
						if i == None:
							totem_options["interface"].append({"ringnumber":1})
							i = get_interface(1)
					else:
						i = None
						
					if i != None:
						if path[3] == "bindnetaddr":
							i["bindnetaddr"] = args
							return "true"
						elif path[3] == "mcastaddr":
							i["mcastaddr"] = args
							return "true"
						elif path[3] == "mcastport":
							try:
								i["mcastport"] = int(args)
								return "true"
							except ValueError:
								return "false"
						elif path[3] == "member":
							member_addr_set = []
							ring_address = "ring%d_addr" % ring_num
							for member_address in args.strip().split(" "):
								colon_pos = member_address.find(":")
								if (colon_pos > -1):
									member_addr_set.append({ring_address:member_address[:colon_pos],"nodeid":member_address[colon_pos+1:]})
								else:
									member_addr_set.append({ring_address:member_address})
							#if ring_num=1,this is interface1. This means I already has interface0, so keep the previous nodelist options
							if (ring_num):
								nodelist_options["node"] += member_addr_set
							else:
								nodelist_options["node"] = member_addr_set
							return "true"
						else:
							return "false"
					else:
						return "false"
				else:
					return "false"
			else:
				return "false"
		else:
			return "false"
		return "false"
class SCR_Agent:
	def __init__(self):
		self.command = ""
		self.path = ""
		self.args = ""
	
	def SCR_Command (self):
		# clean up old data before actually started
		self.command = ""
		self.args = ""
		self.path = ""
			
		#y2debug ("waiting for a command");
		scr_command = sys.stdin.readline().strip()
		
		#y2debug ("newline: %s" % scr_command);
		
		p = re.compile('^`?(\w+)\s*(\(([^,]*)(,\s*(.*))?\s*\))?\s*$')
		r = p.match(scr_command)
		if (r):
			try:
				self.command = r.group(1)
			except IndexError:
				#y2error("No command in %s " % scr_command)
				return
			
			try:
				path = r.group(3)
				if path[0] == '.':
					path = path[1:]
				self.path = path.split('.')

			except IndexError:
				#y2debug("No path in %s " % scr_command)
				return
			try:
				self.args = r.group(5).strip()
				if self.args[0] == '"':
					self.args = self.args[1:]
				if self.args[-1] == '"':
					self.args = self.args[:-1]
			except (IndexError, AttributeError):
				#y2debug("No args in %s " % scr_command)
				return
		else:
			#y2error ("No command in '%s'" % scr_command)
			return

    # <-- SCR_Command
# <-- class SCR_Agent

def main_entry():
	scr_agent = SCR_Agent ()
	openais_agent = OpenAISConf_Parser()

    
	while True:
		scr_agent.SCR_Command ()

		#y2debug("Command %s %s" % (scr_agent.command,scr_agent.path));
		
		if (scr_agent.command == 'Dir' ):
			print openais_agent.doList(scr_agent.path)

		elif (scr_agent.command == 'Read'):
			print openais_agent.doRead(scr_agent.path)

		elif (scr_agent.command == 'Write'):
			print openais_agent.doWrite(scr_agent.path, scr_agent.args)

		elif (scr_agent.command == 'result'):
			break

		else:
			#y2error ("Unknown command: %s" % scr_agent.command)
			print "nil\n"
		try:
			sys.stdout.flush()
		except:
			break
# <-- main
    
if __name__ == "__main__":
	main_entry()
